import type { ResearchConfig } from './types';

export const researchConfig: ResearchConfig = {
  eras: [
    {
      id: 1,
      label: 'Era 1 - Esodo',
      description: 'Prime tecnologie di sopravvivenza e uscita dal sistema.',
      gatewayTechs: ['photonics', 'bio-domes'],
    },
    {
      id: 2,
      label: 'Era 2 - Espansione locale',
      description: 'Espansione stellare, amministrazione e primi cantieri avanzati.',
      gatewayTechs: ['advanced-sensors', 'reinforced-alloys'],
    },
    {
      id: 3,
      label: 'Era 3 - Potere stellare',
      description: 'Logistica interstellare e governance avanzata.',
      gatewayTechs: ['bureaucracy', 'modular-yards'],
    },
    {
      id: 4,
      label: 'Era 4 - Dominio galattico',
      description: 'Propulsione quantica e amministrazione centrale.',
      gatewayTechs: ['deep-space-navigation', 'stellar-logistics'],
    },
  ],
  branches: [
    {
      id: 'physics',
      label: 'Fisica',
      description: 'Energia, sensori e propulsione.',
    },
    {
      id: 'society',
      label: 'Societa',
      description: 'Biologia, amministrazione, tradizioni civili.',
    },
    {
      id: 'engineering',
      label: 'Ingegneria',
      description: 'Materiali, costruzioni e armamenti.',
    },
  ],
  techs: [
    {
      id: 'photonics',
      branch: 'physics',
      name: 'Energia fotonica',
      description: '+10% produzione energia.',
      cost: 40,
      effects: ['energyIncome:+0.1'],
      era: 1,
      clusterId: 'energy-1',
      kind: 'foundation',
      origin: 'standard',
    },
    {
      id: 'advanced-sensors',
      branch: 'physics',
      name: 'Sensori avanzati',
      description: '+10% produzione ricerca.',
      cost: 30,
      effects: ['researchIncome:+0.1'],
      era: 1,
      clusterId: 'sensors-1',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'bio-domes',
      branch: 'society',
      name: 'Bio-cupole',
      description: '+10% produzione cibo.',
      cost: 35,
      effects: ['foodIncome:+0.1'],
      era: 1,
      clusterId: 'bio-1',
      kind: 'foundation',
      origin: 'standard',
    },
    {
      id: 'colony-foundations',
      branch: 'society',
      name: 'Fondamenta colonizzazione',
      description: 'Sblocca la costruzione di navi colonia.',
      cost: 35,
      effects: [],
      era: 1,
      clusterId: 'colony-1',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'science-outfitting',
      branch: 'physics',
      name: 'Allestimento scientifico',
      description: 'Sblocca la costruzione di navi scientifiche.',
      cost: 35,
      effects: [],
      era: 1,
      clusterId: 'science-1',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'orbital-shipyard',
      branch: 'engineering',
      name: 'Cantiere orbitale',
      description: 'Permette di costruire cantieri spaziali con le navi costruttrici.',
      cost: 40,
      effects: [],
      era: 1,
      clusterId: 'yards-1',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'reinforced-alloys',
      branch: 'engineering',
      name: 'Leghe rinforzate',
      description: '+10% produzione minerali.',
      cost: 45,
      effects: ['mineralsIncome:+0.1'],
      era: 1,
      clusterId: 'materials-1',
      kind: 'foundation',
      origin: 'standard',
    },
    {
      id: 'bureaucracy',
      branch: 'society',
      name: 'Burosfera',
      description: '+1 influenza per tick.',
      cost: 45,
      effects: ['influenceFlat:+1'],
      era: 2,
      clusterId: 'admin-1',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'modular-yards',
      branch: 'engineering',
      name: 'Cantieri modulari',
      description: '+10% produzione energia e minerali.',
      cost: 55,
      effects: ['energyIncome:+0.1', 'mineralsIncome:+0.1'],
      prerequisites: ['reinforced-alloys'],
      era: 2,
      clusterId: 'yards-1',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'deep-space-navigation',
      branch: 'physics',
      name: 'Navigazione spazio profondo',
      description: '+10% produzione ricerca.',
      cost: 65,
      effects: ['researchIncome:+0.1'],
      era: 3,
      clusterId: 'nav-3',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'stellar-logistics',
      branch: 'engineering',
      name: 'Logistica stellare',
      description: '+10% produzione minerali.',
      cost: 65,
      effects: ['mineralsIncome:+0.1'],
      era: 3,
      clusterId: 'logistics-3',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'quantum-drives',
      branch: 'physics',
      name: 'Propulsione quantica',
      description: '+12% produzione energia.',
      cost: 90,
      effects: ['energyIncome:+0.12'],
      era: 4,
      clusterId: 'drive-4',
      kind: 'feature',
      origin: 'standard',
    },
    {
      id: 'core-administration',
      branch: 'society',
      name: 'Amministrazione centrale',
      description: '+1.5 influenza per tick.',
      cost: 90,
      effects: ['influenceFlat:+1.5'],
      era: 4,
      clusterId: 'core-admin-4',
      kind: 'feature',
      origin: 'standard',
    },
  ],
  pointsPerResearchIncome: 1,
};
