import type { EconomyConfig } from '@domain/economy';

export const economyConfig: EconomyConfig = {
  startingResources: {
    energy: 100,
    minerals: 80,
    food: 60,
    research: 0,
    influence: 50,
  },
  homeworld: {
    name: 'Aurora Prime',
    kind: 'terrestrial',
    size: 18,
    habitability: 1,
    population: 4,
    baseProduction: {
      energy: 6,
      minerals: 5,
      food: 7,
      research: 3,
      influence: 1,
    },
    upkeep: {
      food: 4,
    },
    districts: {
      generator: 2,
      mining: 2,
      farm: 1,
      research: 1,
    },
  },
  districts: [
    {
      id: 'generator',
      label: 'Distretto energetico',
      description: 'Produce energia sfruttando la rete planetaria.',
      cost: { minerals: 70, energy: 10 },
      buildTime: 5,
      production: { energy: 5 },
      upkeep: { food: 1 },
    },
    {
      id: 'mining',
      label: 'Distretto minerario',
      description: 'Estrae minerali dalle superfici del pianeta.',
      cost: { minerals: 65 },
      buildTime: 5,
      production: { minerals: 5 },
      upkeep: { energy: 1 },
    },
    {
      id: 'farm',
      label: 'Distretto agricolo',
      description: 'Aumenta la produzione di cibo locale.',
      cost: { minerals: 55 },
      buildTime: 4,
      production: { food: 6 },
      upkeep: { energy: 1 },
    },
    {
      id: 'research',
      label: 'Distretto di ricerca',
      description: 'Laboratori e campus scientifici.',
      cost: { minerals: 90, energy: 30 },
      buildTime: 6,
      production: { research: 5 },
      upkeep: { energy: 2 },
    },
  ],
  populationJobs: [
    {
      id: 'workers',
      label: 'Lavoratori',
      description: 'Pop dedicati a miniere, fattorie e infrastrutture.',
      production: { minerals: 1.5, food: 1.5 },
      upkeep: { food: 0.5 },
    },
    {
      id: 'specialists',
      label: 'Specialisti',
      description: 'Tecnici e amministratori per distretti avanzati.',
      production: { energy: 2 },
      upkeep: { food: 0.5, energy: 0.2 },
    },
    {
      id: 'researchers',
      label: 'Ricercatori',
      description: 'Scienziati che aumentano la produzione di ricerca.',
      production: { research: 2.5 },
      upkeep: { food: 0.5, energy: 0.5 },
    },
  ],
  populationAutomation: {
    enabled: true,
    priorities: ['food', 'energy', 'minerals', 'research'],
    deficitThreshold: 0.5,
    surplusThreshold: 3,
  },
  morale: {
    baseStability: 65,
    min: 20,
    max: 95,
    overcrowdingThreshold: 2,
    overcrowdingPenalty: 2,
    deficitThreshold: 25,
    deficitPenalty: 6,
    happinessBonusPerSpecialist: 0.6,
    happinessPenaltyPerWorker: 0.2,
  },
  habitabilityByKind: {
    terrestrial: 0.9,
    desert: 0.6,
    tundra: 0.65,
  },
};
