import type { MilitaryConfig } from './types';

export const militaryConfig: MilitaryConfig = {
  shipyard: {
    queueSize: 4,
    homeSystemDesignId: 'corvette',
    buildCost: {
      minerals: 150,
      energy: 80,
    },
  },
  fleet: {
    baseTravelTicks: 3,
  },
  colonyShipDesignId: 'colony',
  constructionShipDesignId: 'constructor',
  startingShips: {
    science: 0,
    construction: 1,
    colony: 0,
    military: [],
  },
  shipDesigns: [
    {
      id: 'corvette',
      name: 'Classe Aurora',
      role: 'military',
      description: 'Corvetta versatile per pattugliamenti rapidi e schermaglia.',
      buildCost: {
        minerals: 120,
        energy: 40,
      },
      buildTime: 5,
      attack: 6,
      defense: 2,
      hullPoints: 20,
      speed: 1,
    },
    {
      id: 'frigate',
      name: 'Classe Asteria',
      role: 'military',
      description: 'Fregata di linea, buon bilanciamento tra attacco e difesa.',
      buildCost: {
        minerals: 170,
        energy: 70,
      },
      buildTime: 7,
      attack: 10,
      defense: 4,
      hullPoints: 28,
      speed: 0.9,
    },
    {
      id: 'colony',
      name: 'Classe Horizon',
      role: 'colony',
      description: 'Nave colonia con moduli di supporto e stiva ampliata.',
      buildCost: {
        minerals: 150,
        energy: 60,
        food: 20,
      },
      buildTime: 6,
      attack: 0,
      defense: 1,
      hullPoints: 15,
      speed: 0.8,
    },
    {
      id: 'constructor',
      name: 'Classe Atlas',
      role: 'construction',
      description: 'Nave costruttrice per avamposti e infrastrutture orbitali.',
      buildCost: {
        minerals: 110,
        energy: 55,
      },
      buildTime: 6,
      attack: 0,
      defense: 2,
      hullPoints: 18,
      speed: 0.85,
    },
    {
      id: 'science',
      name: 'ISS Pathfinder',
      role: 'science',
      description: 'Nave scientifica per esplorazione e analisi dei sistemi.',
      buildCost: {
        minerals: 90,
        energy: 55,
      },
      buildTime: 6,
      attack: 0,
      defense: 1,
      hullPoints: 14,
      speed: 1.1,
    },
  ],
  templates: [
    {
      id: 'assault',
      base: 'corvette',
      name: 'Variante d Assalto',
      attack: 3,
      defense: 0,
      hull: 2,
      costMultiplier: 1.15,
    },
    {
      id: 'guardian',
      base: 'corvette',
      name: 'Variante Guardia',
      attack: 0,
      defense: 3,
      hull: 3,
      costMultiplier: 1.2,
    },
  ],
};
